---
- hosts: tools-server
  become: true
  gather_facts: yes
  name: install & configure docker service
  roles:
    # install & configure docker service
    - role: roles/docker
      become: true
      tags: docker_setup